import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const rasterforgeFont = localFont({
  src: "../public/font/rasterforge.ttf",
  variable: "--font-rasterforge",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Letters to the Moon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rasterforgeFont.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
